- hosts: localhost
  become: true
  tasks:
  - name: Install generic packages
    apt: name={{item}}
    with_items:
    - htop
    - tmux
  - name: clone nvim
    git:
      repo: https://github.com/neovim/neovim.git
      version: v0.8.0
      dest: /home/skamath/nvim
